#!/bin/bash

echo "Wegger application starting up ..."
sleep 2
project="../api.src"

echo ""
echo ""
echo "Spinning up MSSQL server in docker container using port 1433 on host mapping to 1433 in container ..."
sleep 2
password=$(uuidgen)

echo ""
echo ""
echo "Generated pwd for db: " $password
echo ""
echo ""

docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=${password}" --rm -p 1433:1433 -d --name weggerSQLserver mcr.microsoft.com/mssql/server:2019-latest
database="Wegger"
connectionstring="Server=172.17.0.2;Database=${database};User Id=sa;Password=${password};Trusted_Connection=False;Encrypt=False"

echo ""
echo ""
echo "Configuring connection string for application ..."
sleep 2
dotnet user-secrets init --project $project
dotnet user-secrets set "ConnectionStrings:Wegger" "${connectionstring}" --project $project
echo ""
echo ""

sleep 4

echo "Building web API docker image ..."
sleep 2
docker build -t weggerapi:final $project
echo ""
echo ""

echo "Spinning up wegger api in docker container ..."
sleep 2
docker run -e "ASPNETCORE_ENVIRONMENT=Development" -v "${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets" --rm -p 8080:80 -d --name weggerapiContainer weggerapi:final
echo ""
echo ""
echo "Please wait a couple of seconds ..."
echo ""
echo ""


sleep 5

echo "Launching swagger UI in default host browser ..."
explorer.exe http://localhost:8080/swagger/index.html



